"""job_profile_column_added

Revision ID: 1be952ca9b6f
Revises: 955280db2090
Create Date: 2022-10-14 23:20:44.755303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be952ca9b6f'
down_revision = '955280db2090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_profile', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_profile')
    # ### end Alembic commands ###
